### PR TITLE
Fix Plugin Conflict with Give plugin (previously created 500 server error when viewing site admin)

### LINKED ISSUE #1720: Plugin Conflict: Also using Give plugin currently creates 500 server error when viewing /wp-admin/
I’m getting a 500 server error when trying to access the site admin after updating AMP to the latest version while also running the current version of https://wordpress.org/plugins/give/. Turns out that there’s a conflict with Give which my sites were running into. I also believe the issue could be specific to PHP 7.x (a matter of the number of variables provided to a function vs. what was expected).

I’ve opted to disable AMP to avoid this error until this is fixed since Give is more important to the site than AMP is.

This issue has also been reported at https://wordpress.org/support/topic/http-error-500-after-updating/ (topic was marked as resolved by the topic author after finding they could disable Give, but that doesn't mean the underlying issue has been resolved & those that want to use Give and AMP together are still having the issue.)

### PR DESCRIPTION
**Pull request by KZeni**
Fixes #1720.

### CODE REVIEW

File: includes/validation/class-amp-validated-url-post-type.php [hunk 1]
```diff
@@ -1894,7 +1894,10 @@ public static function print_url_as_title( $post ) {
 	 *
 	 * @return string Title.
 	 */
-	public static function filter_the_title_in_post_list_table( $title, $post ) {
+	public static function filter_the_title_in_post_list_table( $title, $post = '' ) {
+		if($post == ''){
```
Comment (ravinderk) [inline includes/validation/class-amp-validated-url-post-type.php]: @KZeni I found that this function is a callback for `the_title` hook. In that can we need to update the following thing:
1. The second parameter for `the_title` filter in `int` type, so set default value to `0`: https://core.trac.wordpress.org/browser/tags/5.0/src/wp-includes/post-template.php#L158
2. According to point 1, you can also update `$post` param value type to `int` instead of `WP_Post` in function description comment block.
3. Use trinary condition ` $post = empty( $post ) ? get_post() : $post`

File: includes/validation/class-amp-validated-url-post-type.php [hunk 2]
```diff
@@ -1894,7 +1894,10 @@ public static function print_url_as_title( $post ) {
...
+			$post = get_post();
+		}
```
Comment (westonruter) [inline includes/validation/class-amp-validated-url-post-type.php]: I suggest the following change instead:

```diff
- public static function filter_the_title_in_post_list_table( $title, $post ) {
+ public static function filter_the_title_in_post_list_table( $title, $post = null ) {
+     $post = get_post( $post );
```

**Comment by westonruter** [comment]
See also #1723.

File: includes/validation/class-amp-validated-url-post-type.php (hunk 1 above)
Comment (westonruter) [reply includes/validation/class-amp-validated-url-post-type.php]: I found we can simply further. Since `$post` is only used by `get_post_type()`, and since this function takes `null|int|WP_Post` as its type, then we just have to provide an empty default value for `$post`.

**Comment by westonruter** [comment]
I'm rebasing this PR against the `1.0` branch so we can merge it straight into the release branch.

**Comment by westonruter** [comment]
@KZeni could you please double check that the PR fixes the problem as it stands at the moment?
