### PR TITLE
Fix issue with cut 

### LINKED ISSUE #3250: Issue with keyboard cut to clipboard
This bug has been partially addressed in the development of keyboard copy/paste (#2996 ). However, this ticket has been created to individually track the specific bug that @spacedmonkey is working on.

### PR DESCRIPTION
**Pull request by spacedmonkey**
Fix cut via keyboard by using state based clipboard over the browser clipboard. This copies the logic used in the right click menu logic. 

Fixes #3250

### CODE REVIEW

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 1]
```diff
@@ -45,20 +49,26 @@ function CopyPasteHandler( { children, onCopy, onCut, clientId, isSelected } ) {
...
-		// otherwise throw an invalid argument error, so we try the standard
-		// arguments first, then fallback to `Text` if they fail.
-		try {
-			plainText = clipboardData.getData( 'text/plain' );
-			html = clipboardData.getData( 'text/html' );
-		} catch ( error1 ) {
+		if ( getCopiedMarkupState().length ) {
+			plainText = getCopiedMarkupState();
+			html = getCopiedMarkupState();
+			clearCopiedMarkup();
```
Comment (barklund) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: `clear`? So you can only paste once? Is this by design?

Comment (swissspidy) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: The same limitation existed in #3083 but was removed in ddce16429cb85a5b10ec5429d62ce88ac5866723. I don't see why cut should now behave differently than copy.

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 2]
```diff
@@ -13,27 +13,31 @@ import { withDispatch, useSelect, useDispatch } from '@wordpress/data';
...
 			return {
 				isFirstPage: getBlockOrder().indexOf( clientId ) === 0,
 				canUserUseUnfilteredHTML: __experimentalCanUserUseUnfilteredHTML,
+				getCopiedMarkupState: getCopiedMarkup,
 			};
 		}, [ clientId ]
 	);
 
 	const { insertBlocks } = useDispatch( 'core/block-editor' );
+	const { clearCopiedMarkup } = useDispatch( 'amp/story' );
```
Comment (swissspidy) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: Remove usage of `clearCopiedMarkup`

```suggestion
```

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 1 above)
Comment (swissspidy) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]:
```suggestion
```

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 3]
```diff
@@ -100,6 +110,7 @@ export default withDispatch( ( dispatch, ownProps, { select } ) => {
 		hasMultiSelection,
 	} = select( 'core/block-editor' );
 	const { clearCopiedMarkup, setCopiedMarkup } = dispatch( 'amp/story' );
```
Comment (swissspidy) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]:
```suggestion
	const { setCopiedMarkup } = dispatch( 'amp/story' );
```

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: In my testing it now behaved like this:

1. Cut block A
1. Block A is removed and block b is selected
1. Select page so that pasting works
1. Paste (expectation: copy of A is inserted)
1. Newly inserted block A\' is selected
1. Cut block B
1. Select page so that pasting works
1. Paste (expectation: copy of B is inserted)
1. Newly inserted block B\' is selected
1. Select page so that pasting works
1. Paste (expectation: copy of B is inserted)
1. Newly inserted block A\'' is selected

I suppose this is because Cmd+X adds the content to both the store and the actual clipboard, and after pasting it is cleared from the store but not the actual clipboard. That means on subsequent paste it will paste the old information.

**Comment by spacedmonkey** [comment]
Spent a little more time working on this. Feel like we currently have is much cleaner than what we had. Did a little refactoring on this one as well, couldnt help myself.

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 4]
```diff
@@ -123,24 +125,36 @@ export default withDispatch( ( dispatch, ownProps, { select } ) => {
...
+
+		// Make sure that setCopiedMarkup finishes before doing anything else.
+		setCopiedMarkup( serialized ).then( () => {
+			copyTextToClipBoard( serialized );
+
+			if ( isCut ) {
+				const pageClientId = getCurrentPage();
+				for ( const clientId of selectedBlockClientIds ) {
+					// On removing block, change focus to the page, to make sure that editor doesn't get confused.
+					selectBlock( pageClientId );
```
Comment (barklund) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: We have to do this inside the loop? Or is the loop actually a little superfluous, as we can only ever have a single block selected?

File: assets/src/stories-editor/components/right-click-menu/index.js [hunk 5]
```diff
@@ -60,7 +61,7 @@ const RightClickMenu = ( props ) => {
 	const blockClientIds = castArray( clientIds );
 	const firstBlockClientId = blockClientIds[ 0 ];
 	const block = getBlock( firstBlockClientId );
-	const isPageBlock = block ? 'amp/amp-story-page' === block.name : false;
+	const isPageBlock = isStoryBlock( firstBlockClientId );
```
Comment (barklund) [inline assets/src/stories-editor/components/right-click-menu/index.js]: The function and the variable are inconsistently named here. Which is it?

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: Doing this in the loop, makes sure that if multiple blocks are copied, that the editor doesnt get confused and try and select a block that has been removed. Putting the code here, is not an issue, as most of the time, only one block is being copied anyway..

File: assets/src/stories-editor/components/right-click-menu/index.js (hunk 5 above)
Comment (spacedmonkey) [reply assets/src/stories-editor/components/right-click-menu/index.js]: No they are not.

**Comment by spacedmonkey** [comment]
Fixes #3250

File: assets/src/stories-editor/helpers/index.js [hunk 6]
```diff
@@ -2132,3 +2132,14 @@ export const startAnimation = ( block, animationType, animationDuration, animati
...
 	blockElement.addEventListener( 'animationend', callback, { once: true } );
 };
+
+/**
+ * Check if block is page block.
+ *
+ * @param {string} clientId Block client ID.
+ * @return {boolean} Boolean if block is / is not a page block.
+ */
+export const isStoryBlock = ( clientId ) => {
```
Comment (swissspidy) [inline assets/src/stories-editor/helpers/index.js]: "Check if block is page block."

Then this should better be named `isPageBlock`.

Comment (spacedmonkey) [reply assets/src/stories-editor/helpers/index.js]: Fixed https://github.com/ampproject/amp-wp/pull/3246/commits/ce6b984e34ce14bbd74859fd9c037066cab8799f

File: assets/src/stories-editor/components/right-click-menu/index.js (hunk 5 above)
Comment (spacedmonkey) [reply assets/src/stories-editor/components/right-click-menu/index.js]: Fixed https://github.com/ampproject/amp-wp/pull/3246/commits/ce6b984e34ce14bbd74859fd9c037066cab8799f

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 1 above)
Comment (spacedmonkey) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: If you cut text normally, you can paste it as many times as you want, as it is on the clipboard. So what is the expected behavior here.

Comment (spacedmonkey) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: This is out of date this call to `clearCopiedMarkup` was removed.

Comment (spacedmonkey) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: :100:

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 7]
```diff
@@ -55,10 +58,9 @@ function CopyPasteHandler( { children, onCopy, onCut, clientId, isSelected } ) {
 			try {
 				html = clipboardData.getData( 'Text' );
 			} catch ( error2 ) {
-				// Some browsers like UC Browser paste plain text by default and
-				// don't support clipboardData at all, so allow default
-				// behaviour.
-				return;
+				// If everything gones wrong, fallback to state based clipboard.
```
Comment (swissspidy) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]:
```suggestion
				// If everything goes wrong, fall back to state based clipboard.
```

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 4 above)
Comment (swissspidy) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: > "[...] try and select a block that has been removed"

Sounds like something that should be added as an inline doc.

Just "to make sure that editor doesn't get confused" alone is not very helpful.

**Comment by spacedmonkey** [comment]
Will this go in 1.3 or 1.3.1? @swissspidy If 1.3.1, can you change the milestone?

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js [hunk 8]
```diff
@@ -123,24 +125,36 @@ export default withDispatch( ( dispatch, ownProps, { select } ) => {
...
+		const isCut = ( event.type === 'cut' );
+
+		// Make sure that setCopiedMarkup finishes before doing anything else.
+		setCopiedMarkup( serialized ).then( () => {
+			copyTextToClipBoard( serialized );
+
+			if ( isCut ) {
+				const pageClientId = getCurrentPage();
+				for ( const clientId of selectedBlockClientIds ) {
+					// On removing block, change focus to the page, to make sure that editor doesn't get confused.
```
Comment (swissspidy) [inline assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]:
```suggestion
					// On removing block, change focus to the page, to make sure that editor doesn't get confused and tries to select an already removed block.
```

File: assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/stories-editor/blocks/amp-story-page/copy-paste-handler.js]: :100:
