### PR TITLE
Fix and consolidate some of the i18n strings

### LINKED ISSUE #2198: I18N String review
I did some translation work this week and am happy to say that the AMP plugin is now almost fully translated to German (formal + informal) and German Switzerland (formal + informal) 💪

Admittedly, it was kinda hard to translate the plugin as the majority of the strings is very long and technical. Often times there is also a lack of context.

Because of this, I am opening this issue as some sort of tracking ticket for improving the i18n strings over time.

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #2198.

### CODE REVIEW

File: assets/src/stories-editor/blocks/amp-story-post-date/index.js [hunk 1]
```diff
@@ -17,9 +17,8 @@ export const settings = {
 	category: 'common',
 	icon: 'clock',
 	keywords: [
-		__( 'post', 'amp' ),
+		__( 'story', 'amp' ),
 		__( 'publish date', 'amp' ),
-		__( 'published date', 'amp' ),
 		__( 'date', 'amp' ),
```
Comment (miina) [inline assets/src/stories-editor/blocks/amp-story-post-date/index.js]: ^ This is also redundant since `publish date` already covers the `date` keyword.

File: assets/src/stories-editor/components/higher-order/with-amp-story-settings.js [hunk 2]
```diff
@@ -513,7 +513,7 @@ export default createHigherOrderComponent(
 									} }
 								/>
 								<RangeControl
-									label={ __( 'Background Opacity', 'amp' ) }
+									label={ __( 'Opacity', 'amp' ) }
```
Comment (miina) [inline assets/src/stories-editor/components/higher-order/with-amp-story-settings.js]: Are you removing this for translation purposes or generally as well? Wondering if it's clear without it that it's for the background only? I guess it should be.

File: includes/admin/class-amp-admin-pointers.php [hunk 3]
```diff
@@ -96,7 +96,7 @@ private function get_pointers() {
 				array(
 					'selector'        => '#menu-posts-' . AMP_Story_Post_Type::POST_TYPE_SLUG,
 					'heading'         => __( 'AMP', 'amp' ),
-					'description'     => __( 'Head over here to create your first AMP story.', 'amp' ),
+					'description'     => __( 'Head over here to create your first story.', 'amp' ),
```
Comment (miina) [inline includes/admin/class-amp-admin-pointers.php]: Looks like you've removed `.` from some of the descriptions, should it be removed from here as well?

File: assets/src/stories-editor/components/inserter/index.js [hunk 4]
```diff
@@ -112,7 +112,7 @@ class Inserter extends Component {
 				position={ position }
 				onToggle={ this.onToggle }
 				expandOnMobile
-				headerTitle={ __( 'Add a block', 'amp' ) }
+				headerTitle={ __( 'Add block', 'amp' ) }
```
Comment (miina) [inline assets/src/stories-editor/components/inserter/index.js]: I'm not an English expert at all but wouldn't `Add block` be used if it's for a specific block and `Add a block` more accurate here?

File: includes/admin/class-amp-admin-pointers.php (hunk 3 above)
Comment (miina) [reply includes/admin/class-amp-admin-pointers.php]: Or I guess this is a different kind of description?

File: assets/src/stories-editor/components/higher-order/with-amp-story-settings.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/stories-editor/components/higher-order/with-amp-story-settings.js]: Mainly because it should be clear enough and because we already use `__( 'Opacity', 'amp' )` as a string in the editor. Makes things consistent and results in one string less to translate.

File: includes/admin/class-amp-admin-pointers.php (hunk 3 above)
Comment (swissspidy) [reply includes/admin/class-amp-admin-pointers.php]: This is the text within an admin pointer, which is quite a different area from the stories editor.

File: assets/src/stories-editor/components/inserter/index.js (hunk 4 above)
Comment (swissspidy) [reply assets/src/stories-editor/components/inserter/index.js]: Actually, I think we should use `element` instead of `block` here anyway.

Mainly removed the `a` to consolidate strings.

File: assets/src/stories-editor/blocks/amp-story-post-date/index.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/stories-editor/blocks/amp-story-post-date/index.js]: Makes sense!

File: assets/src/stories-editor/blocks/amp-story-page/edit.js [hunk 5]
```diff
@@ -338,7 +338,7 @@ class PageEdit extends Component {
 								{ !! mediaId &&
 								<MediaUploadCheck>
 									<Button onClick={ () => setAttributes( { mediaUrl: undefined, mediaId: undefined, mediaType: undefined } ) } isLink isDestructive>
-										{ VIDEO_BACKGROUND_TYPE === mediaType ? __( 'Remove Video', 'amp' ) : __( 'Remove image', 'amp' ) }
+										{ _x( 'Remove', 'background media', 'amp' ) }
```
Comment (kienstra) [inline assets/src/stories-editor/blocks/amp-story-page/edit.js]: Good idea to simplify this to 'Remove.' It's inside the 'Background Media' section, so it's clear enough what it's removing:

remove-here

File: assets/src/stories-editor/components/inserter/index.js (hunk 4 above)
Comment (kienstra) [reply assets/src/stories-editor/components/inserter/index.js]: Yeah, this would probably be fine with or without `a`.
