### PR TITLE
Sanitize widgets during post-processing

### LINKED ISSUE #4492: Replacing widgets for Categories, Archives, and Text causes theme/plugin incompatibilities
Plugin Version 1.5.1
WordPress Version 5.4

the file: amp/includes/widgets/class-amp-widget-categories.php
make my theme sidebar.php's WP_Widget_Categories not work.
```php
<?php
if(is_home() || is_page()){
    the_widget( 'WP_Widget_Categories', array(
        'count'		=>	0,
        'dropdown'	=>	0
    ), array(
        'before_widget'	=>	'<aside id="categories" class="widget well widget_categories">',
        'after_widget'	=>	'</aside>',
        'before_title'	=>	'<h2 class="widget-title">',
        'after_title'	=>	'</h2>',
    ) );
}
```

Now I clear the content of amp/includes/widgets/class-amp-widget-categories.php
So that I can show the Categories in the index. Maybe you can check if there's some problem of this code.

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Deprecate overriding of widgets and instead sanitize them during post-processing.

Addresses issue #4492.

### All Widgets

The AMP-specific overrides for the Text widget, Archives widget, and Categories widget has been eliminated. Themes can now reliably use `the_widget( 'WP_Widget_Categories )` without getting an error or having to supply an AMP-alternative. The AMP-specific fixes are now applied during post-processing.

### Archives Widget

AMP-to-AMP linking is now preserved when selecting to navigate via a dropdown in the Archives widget.

### Text Widget

This PR fixes displaying videos and iframes in a Text widget. WordPress core in `WP_Widget_Text::inject_video_max_width_style()` removes the `width` and `height` attributes from `video` and `iframe` elements in an attempt to give overly-wide elements an “intrinsic” size in the sidebar, but this does not work in AMP as the dimensions must be defined up front. Also, the `video` and `iframe` elements are automatically converted into `amp-video` and `amp-iframe` with the `intrinsic` layout so they will automatically be sized to fit the container and not larger. Therefore, this adds a hack to preserve those original attributes when applying filters to then restore them during post-processing.

This PR also fixes the default styles for `video` shortcode in the content, by providing a bottom margin as well as a max-width which would normally have been supplied by MediaElement.js, but which is not included on the AMP page.

Before:

Screen Shot 2020-04-21 at 15 55 26

After:

image

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

File: includes/embeds/class-amp-core-block-handler.php [hunk 1]
```diff
@@ -178,4 +180,61 @@ public function ampify_cover_block( $block_content, $block ) {
...
+			// Nothing to do if there is not a select element.
+			return;
+		}
+
+		$id++;
+
+		$form_node->setAttribute( 'target', '_top' );
+		$form_node->setAttribute( 'id', $id );
+
+		$select_element[0]->setAttribute( 'on', sprintf( 'change:%s.submit', esc_attr( $id ) ) );
```
Comment (westonruter) [inline includes/embeds/class-amp-core-block-handler.php]: No escaping needed.

```suggestion
		$select_element[0]->setAttribute( 'on', sprintf( 'change:%s.submit', $id ) );
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 2]
```diff
@@ -178,4 +180,61 @@ public function ampify_cover_block( $block_content, $block ) {
...
+
+	/**
+	 * Process a category widget.
+	 *
+	 * @param DOMElement $form_node Form node retrieved from the widget.
+	 */
+	private function process_category_widget( DOMElement $form_node ) {
+		static $id = 0;
+
+		$select_element = $form_node->getElementsByTagName( 'select' );
```
Comment (westonruter) [inline includes/embeds/class-amp-core-block-handler.php]: Better to check for a select with a certain name.

File: includes/embeds/class-amp-core-block-handler.php [hunk 3]
```diff
@@ -178,4 +180,61 @@ public function ampify_cover_block( $block_content, $block ) {
...
+		$select_element[0]->setAttribute( 'on', sprintf( 'change:%s.submit', esc_attr( $id ) ) );
+	}
+
+	/**
+	 * Process an archive widget.
+	 *
+	 * @param DOMElement $select_node Select node retrieved from the widget.
+	 */
+	private function process_archive_widget( DOMElement $select_node ) {
+		$select_node->setAttribute( 'on', 'change:AMP.navigateTo(url=event.value)' );
```
Comment (westonruter) [inline includes/embeds/class-amp-core-block-handler.php]: This needs to remove the `script` element as well. Same for the category widget.

**Comment by westonruter** [comment]
I'm updating the tests.

File: tests/php/test-class-amp-core-block-handler.php [hunk 4]
```diff
@@ -177,4 +177,128 @@ public function test_ampify_cover_block() {
...
+		}
+		$ids = [];
+		foreach ( $forms as $form ) {
+			$this->assertTrue( $form->hasAttribute( 'id' ) );
+			$ids[] = $form->getAttribute( 'id' );
+		}
+		$this->assertCount( $instance_count, array_unique( $ids ) );
+	}
+
+
```
Comment (schlessera) [inline tests/php/test-class-amp-core-block-handler.php]:
```suggestion

```

File: tests/php/test-class-amp-core-block-handler.php [hunk 5]
```diff
@@ -177,4 +177,128 @@ public function test_ampify_cover_block() {
...
+			);
+		}
+		$html = ob_get_clean();
+
+		$dom = AMP_DOM_Utils::get_dom_from_content( $html );
+
+		/**
+		 * Elements.
+		 *
+		 * @var DOMElement $select
```
Comment (schlessera) [inline tests/php/test-class-amp-core-block-handler.php:285]:
```suggestion
		 * @var DOMElement $selects
```

File: tests/php/test-class-amp-core-block-handler.php [hunk 6]
```diff
@@ -177,4 +177,128 @@ public function test_ampify_cover_block() {
...
+		 * @var DOMElement $form
```
Comment (schlessera) [inline tests/php/test-class-amp-core-block-handler.php:212]:
```suggestion
		 * @var DOMElement $selects
		 * @var DOMElement $forms
```

File: tests/php/test-class-amp-core-block-handler.php [hunk 7]
```diff
@@ -177,4 +177,128 @@ public function test_ampify_cover_block() {
...
+
+		$embed = new AMP_Core_Block_Handler();
+		$embed->register_embed();
+		$embed->sanitize_raw_embeds( $dom );
+
+		$error_count = 0;
+		$sanitizer   = new AMP_Tag_And_Attribute_Sanitizer(
+			$dom,
+			[
+				'validation_error_callback' => static function() use ( &$error_count ) {
```
Comment (schlessera) [inline tests/php/test-class-amp-core-block-handler.php]:
```suggestion
				'validation_error_callback' => static function () use ( &$error_count ) {
```

File: tests/php/test-class-amp-core-block-handler.php [hunk 8]
```diff
@@ -177,4 +177,128 @@ public function test_ampify_cover_block() {
...
+		$embed->sanitize_raw_embeds( $dom );
+
+		$sanitizer = new AMP_Form_Sanitizer( $dom );
+		$sanitizer->sanitize();
+
+		$error_count = 0;
+		$sanitizer   = new AMP_Tag_And_Attribute_Sanitizer(
+			$dom,
+			[
+				'validation_error_callback' => static function() use ( &$error_count ) {
```
Comment (schlessera) [inline tests/php/test-class-amp-core-block-handler.php]:
```suggestion
				'validation_error_callback' => static function () use ( &$error_count ) {
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 9]
```diff
@@ -178,4 +180,75 @@ public function ampify_cover_block( $block_content, $block ) {
...
+	private function process_archives_widgets( Document $dom ) {
+
+		$widget_containers = $dom->xpath->query( '//*[ contains( @class, "widget_archive" ) ]' );
+		foreach ( $widget_containers as $widget_container ) {
+			$select = $dom->xpath->query( './/select[ @name = "archive-dropdown" ]', $widget_container )->item( 0 );
+			if ( ! $select instanceof DOMElement ) {
+				continue;
+			}
+
+			$select->setAttribute( 'on', 'change:AMP.navigateTo(url=event.value)' );
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]: Use the `add_amp_action()` helper here to ensure a potential previous action is not just overwritten.
```suggestion
			AMP_DOM_Utils::add_amp_action( $select, 'change', 'AMP.navigateTo(url=event.value)' );
```

File: tests/php/test-class-amp-core-block-handler.php (hunk 5 above)
Comment (westonruter) [reply tests/php/test-class-amp-core-block-handler.php:285]: This is intended actually. The type defs are for when looping over these below.

File: tests/php/test-class-amp-core-block-handler.php (hunk 6 above)
Comment (westonruter) [reply tests/php/test-class-amp-core-block-handler.php:212]: This is intended actually. The type defs are for when looping over these below.

File: includes/embeds/class-amp-core-block-handler.php [hunk 10]
```diff
@@ -178,4 +180,75 @@ public function ampify_cover_block( $block_content, $block ) {
...
+	 * Process "Categories" widgets.
+	 *
+	 * @since 1.5.2
+	 *
+	 * @param Document $dom Document.
+	 */
+	private function process_categories_widgets( Document $dom ) {
+		static $count = 0;
+
+		$widget_containers = $dom->xpath->query( '//*[ contains( @class, "widget_categories" ) ]' );
```
Comment (pierlon) [inline includes/embeds/class-amp-core-block-handler.php]: This isn't matching widgets that are added via `the_widget()`. For example:

```php
$the_widget_args = array(
		'before_widget' => '<div class="widget">',
		'after_widget'  => '</div>',
		'before_title'  => '<div class="widget-title"><h3>',
		'after_title'   => '</h3></div>',
	);

the_widget( 'WP_Widget_Categories', [ 'title' => 'Categories', 'dropdown' => true ], $the_widget_args )
```

could generate:

```html
<div class="widget">
    <div class="widget-title">
        <h3>Categories</h3>
    </div>
    <form action="https://wordpressdev.lndo.site" method="get"><label class="screen-reader-text"
            for="cat">Categories</label><select name="cat" id="cat" class="postform">
            <option value="-1">Select Category</option>
            <option class="level-0" value="1">Uncategorized</option>
        </select>
    </form>
    <script>
        /* <![CDATA[ */
        (function () {
            var dropdown = document.getElementById("cat");
            function onCatChange() {
                if (dropdown.options[dropdown.selectedIndex].value > 0) {
                    dropdown.parentNode.submit();
                }
            }
            dropdown.onchange = onCatChange;
        })();
/* ]]> */
    </script>

</div>
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 11]
```diff
@@ -178,4 +180,75 @@ public function ampify_cover_block( $block_content, $block ) {
...
+	/**
+	 * Process "Archives" widgets.
+	 *
+	 * @since 1.5.2
+	 *
+	 * @param Document $dom Select node retrieved from the widget.
+	 */
+	private function process_archives_widgets( Document $dom ) {
+
+		$widget_containers = $dom->xpath->query( '//*[ contains( @class, "widget_archive" ) ]' );
```
Comment (pierlon) [inline includes/embeds/class-amp-core-block-handler.php]: This isn't matching widgets that are added via `the_widget()`. For example:

```php
$the_widget_args = array(
		'before_widget' => '<div class="widget">',
		'after_widget'  => '</div>',
		'before_title'  => '<div class="widget-title"><h3>',
		'after_title'   => '</h3></div>',
	);

the_widget( 'WP_Widget_Archives', [ 'title' => 'Archive', 'dropdown' => true ], $the_widget_args );
```

could generate:

```html
<div class="widget">
    <div class="widget-title">
        <h3>Archive</h3>
    </div> <label class="screen-reader-text" for="archives-dropdown--1">Archive</label>
    <select id="archives-dropdown--1" name="archive-dropdown">

        <option value="">Select Month</option>
        <option value="https://wordpressdev.lndo.site/2020/04/"> April 2020 </option>
        <option value="https://wordpressdev.lndo.site/2020/03/"> March 2020 </option>

    </select>

    <script>
        /* <![CDATA[ */
        (function () {
            var dropdown = document.getElementById("archives-dropdown--1");
            function onSelectChange() {
                if (dropdown.options[dropdown.selectedIndex].value !== '') {
                    document.location.href = this.options[this.selectedIndex].value;
                }
            }
            dropdown.onchange = onSelectChange;
        })();
/* ]]> */
    </script>

</div>
```

Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: That's true, but if the user is suppressing the class name from appearing then they have bigger problems I think. Themes need that class name to be present in order to style the widgets properly.

File: includes/embeds/class-amp-core-block-handler.php (hunk 10 above)
Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: https://github.com/ampproject/amp-wp/pull/4515#discussion_r403063631

File: includes/embeds/class-amp-core-block-handler.php (hunk 11 above)
Comment (pierlon) [reply includes/embeds/class-amp-core-block-handler.php]: There are some themes that do override the class name: https://wpdirectory.net/search/01E508QBAE335DVKC95FAV11TD

Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: Humm. They do seem to retain the required class name in the class, e.g. `widget_categories`:

> image

The exception is Kale which doesn't do it for every widget:

> image

Which may be bug?

Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: I suppose this can be hardened by looking for element that matches the query:

```
//select[ @name = 'archive-dropdown' and starts-with( @id, 'archives-dropdown-' ) ]
```

And then the parent element of that is the widget container. That would be invariable.

File: includes/embeds/class-amp-core-block-handler.php (hunk 10 above)
Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: Hardening this would be to use this query to obtain the `select`:

```
//form/select[ @name = 'cat' ]
```

I don't think it is safe to also query for `@id = "cat"` because this seems like a bug in core, where the ID needs to be auto-incremented.

And the grandparent is the widget container. Verifying it has a `script` with the expected contents should then also be done.

File: includes/embeds/class-amp-core-block-handler.php (hunk 11 above)
Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: See bdeb953

File: includes/embeds/class-amp-core-block-handler.php (hunk 10 above)
Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: See bdeb953

**Comment by westonruter** [comment]
I'm struggling to find a way to port `\AMP_Widget_Text::inject_video_max_width_style()` to the sanitizer.

**Comment by westonruter** [comment]
Bumping this to v1.5.3

**Comment by westonruter** [comment]
Build for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/4513199/amp.zip) (v1.6.0-alpha-20200422T003801Z-499c40199)

**Comment by westonruter** [comment]
@pierlon @schlessera Are you happy with the changes here?

File: assets/css/src/amp-default.css [hunk 12]
```diff
@@ -77,3 +77,17 @@ amp-carousel .amp-wp-gallery-caption {
...
+
+/*
+ * Replicate bottom-margin which is added to .mejs-container to by theme styles, although it varies;
+ * - 1.5em in Twenty Seventeen
+ * - 24px in Twenty Eleven, Twenty Thirteen and Twenty Twelve
+ * Other themes set the bottom margin on direct descendants of the .entry-content, in which case this will be overridden.
+ *
+ * The max-width:100% is normally applied by to .mejs-container by wp-mediaelement.css but this stylesheet is not
+ * included iN AMP, so this is why it is included here.
+ */
```
Comment (schlessera) [inline assets/css/src/amp-default.css]:
```suggestion
/*
 * Replicate bottom-margin which is added to .mejs-container by theme styles, although it varies;
 * - 1.5em in Twenty Seventeen
 * - 24px in Twenty Eleven, Twenty Thirteen and Twenty Twelve
 * Other themes set the bottom margin on direct descendants of the .entry-content, in which case this will be overridden.
 *
 * The max-width: 100% is normally applied by to .mejs-container by wp-mediaelement.css but this stylesheet is not
 * included in AMP, so this is why it is included here.
 */
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 13]
```diff
@@ -178,4 +201,156 @@ public function ampify_cover_block( $block_content, $block ) {
...
+
+	/**
+	 * Process "Categories" widgets.
+	 *
+	 * @since 1.6
+	 *
+	 * @param Document $dom Document.
+	 */
+	private function process_categories_widgets( Document $dom ) {
+		static $count = 0;
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]: This should be a property instead. I've been bitten with static variables multiple times now with the optimizer, especially during tests.

Using properties makes sure we don't get unexpected results across tests or when using sanitizers multiple times, for whatever reason.

File: includes/embeds/class-amp-core-block-handler.php [hunk 14]
```diff
@@ -178,4 +201,156 @@ public function ampify_cover_block( $block_content, $block ) {
...
+	/**
+	 * Process "Archives" widgets.
+	 *
+	 * @since 1.6
+	 *
+	 * @param Document $dom  Select node retrieved from the widget.
+	 * @param array    $args Args passed to sanitizer.
+	 */
+	private function process_archives_widgets( Document $dom, $args = [] ) {
+
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]:
```suggestion
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 15]
```diff
@@ -178,4 +201,156 @@ public function ampify_cover_block( $block_content, $block ) {
...
+	/**
+	 * Process "Text" widgets.
+	 *
+	 * @since 1.6
+	 * @see AMP_Core_Block_Handler::preserve_widget_text_element_dimensions()
+	 *
+	 * @param Document $dom  Select node retrieved from the widget.
+	 */
+	private function process_text_widgets( Document $dom ) {
+
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]:
```suggestion
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 16]
```diff
@@ -178,4 +201,156 @@ public function ampify_cover_block( $block_content, $block ) {
...
+		return $content;
+	}
+
+	/**
+	 * Process "Text" widgets.
+	 *
+	 * @since 1.6
+	 * @see AMP_Core_Block_Handler::preserve_widget_text_element_dimensions()
+	 *
+	 * @param Document $dom  Select node retrieved from the widget.
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]:
```suggestion
	 * @param Document $dom Select node retrieved from the widget.
```

File: includes/embeds/class-amp-core-block-handler.php [hunk 17]
```diff
@@ -178,4 +201,156 @@ public function ampify_cover_block( $block_content, $block ) {
...
+			 * Remove inline width style which is added to video shortcode but which overruns the container.
+			 * Normally this width gets overridden by wp-mediaelement.css to be max-width: 100%, but since
+			 * MediaElement.js is not used in AMP this stylesheet is not included. In any case, videos in AMP are
+			 * responsive so this is built-in. Note also the style rule for .wp-video in amp-default.css.
+			 */
+			foreach ( $dom->xpath->query( './/div[ @class = "wp-video" and @style ]' ) as $element ) {
+				$element->removeAttribute( 'style' );
+			}
+		}
+
```
Comment (schlessera) [inline includes/embeds/class-amp-core-block-handler.php]:
```suggestion
```

File: includes/widgets/class-amp-widget-archives.php [hunk 18]
```diff
@@ -4,11 +4,15 @@
...
  * @package AMP
+ * @codeCoverageIgnore
  */
 
+_deprecated_file( __FILE__, '1.6' );
+
 /**
  * Class AMP_Widget_Archives
  *
+ * @deprecated As of 1.5.2 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```
Comment (schlessera) [inline includes/widgets/class-amp-widget-archives.php]:
```suggestion
 * @deprecated As of 1.6 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```

File: includes/widgets/class-amp-widget-categories.php [hunk 19]
```diff
@@ -4,11 +4,15 @@
...
  * @package AMP
+ * @codeCoverageIgnore
  */
 
+_deprecated_file( __FILE__, '1.6' );
+
 /**
  * Class AMP_Widget_Categories
  *
+ * @deprecated As of 1.5.2 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```
Comment (schlessera) [inline includes/widgets/class-amp-widget-categories.php]:
```suggestion
 * @deprecated As of 1.6 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```

File: includes/widgets/class-amp-widget-text.php [hunk 20]
```diff
@@ -4,13 +4,17 @@
...
  */
 
+_deprecated_file( __FILE__, '1.6' );
+
 if ( class_exists( 'WP_Widget_Text' ) ) {
 	/**
 	 * Class AMP_Widget_Text
 	 *
 	 * @since 0.7.0
+	 * @deprecated As of 1.5.2 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```
Comment (schlessera) [inline includes/widgets/class-amp-widget-text.php]:
```suggestion
	 * @deprecated As of 1.6 the AMP_Core_Block_Handler will sanitize the core widgets instead.
```

File: includes/embeds/class-amp-core-block-handler.php (hunk 13 above)
Comment (westonruter) [reply includes/embeds/class-amp-core-block-handler.php]: Good point. Done in c51cad184.

**Comment by pierlon** [comment]
Looks good! LGTM :shipit:.
