### PR TITLE
Reload video player after changing background video

### LINKED ISSUE #2616: Video Selection - Incorrect Video in Editor as Background Media
Steps to reproduce

- selected the small story_video_dog.mp4 as Background Media.
- appeared fine in editor (look at that dog go!):
image
- decided to Change Media
- selected video IMG_20190429_130647_exported_stabilized_1524510947523174136.mp4 (fountain) from Media Library
- appeared in editor with warning/recommendation:
image
- so then decided to Change Media BACK to the originally selected "dog" video
- change didn't take effect in editor:
image

NOTE: Preview DOES show the correct "doggy" video - it's just not right in the editor

### PR DESCRIPTION
**Pull request by swissspidy**
While everything was working correctly and the video player was properly getting the new video URL and all, the player needs to be reloaded when the video source changes. Otherwise it continues playing the previous one.

Fixes #2616.

### CODE REVIEW

File: assets/src/stories-editor/blocks/amp-story-page/edit.js [hunk 1]
```diff
@@ -133,6 +135,15 @@ class PageEdit extends Component {
 		} );
 	}
 
+	componentDidUpdate( prevProps ) {
+		if (
+			VIDEO_BACKGROUND_TYPE === this.props.attributes.mediaType &&
+			this.props.attributes.mediaUrl !== prevProps.attributes.mediaUrl &&
+			this.videoPlayer.current ) {
```
Comment (miina) [inline assets/src/stories-editor/blocks/amp-story-page/edit.js]: The `)` and `}` could probably be on the next line for readability.

Comment (swissspidy) [reply assets/src/stories-editor/blocks/amp-story-page/edit.js]: Totally. Looks like ESLint doesn't catch these things 🤷‍♂
