### PR TITLE
Remove invalid processing instructions

### LINKED ISSUE #3409: Erroneous XML processing instructions (e.g. <?php ?>) are not sanitized
As reported on the [support forums](https://wordpress.org/support/topic/amp-1-3-0-validation-errors/), upon upgrading to AMP 1.3 they they started getting the AMP validator complaining about validation errors for this markup:

```html
<?php
$schema = get_post_meta(get_the_ID(), 'schema', true);
if(!empty($schema)) {
echo $schema;
}
?>
```

Naturally this is a bug since the PHP code is getting incorrectly included on the page. But still this `<?php ... ?>` processing instruction and others like it should be getting sanitized. It was actually getting removed in the previous version of the plugin, with an error code of `unknown`:

image

We should restore this behavior, or rather add a more specific error code like `invalid_processing_instruction`. The validator doesn't apparently allow _any_ processing instructions, including:

* 🚫 `<?xml version="1.0" encoding="UTF-8" ?>`
* 🚫 `<?xml-stylesheet type="text/xsl" href="style.xsl"?>`
* 🚫 `<?php /*...*/ ?>`

This would be a regression likely introduced by #3243.

### PR DESCRIPTION
**Pull request by pierlon**
Co-Authored-By: Weston Ruter <westonruter@google.com>

## Summary

Remove all invalid processing instructions and also display the `invalid_processing_instruction` error code for such occurrences.

## Screenshot:

image

Fixes #3409.

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

File: tests/php/test-tag-and-attribute-sanitizer.php [hunk 1]
```diff
@@ -1682,6 +1682,13 @@ static function() {
 				[],
 				[ 'invalid_element' ],
 			],
+
+			'invalid_php_pi'                               => [
```
Comment (westonruter) [inline tests/php/test-tag-and-attribute-sanitizer.php]: Please also add a test for (formerly) very-common `<?xml ... ?>` processing instruction.

File: includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php [hunk 2]
```diff
@@ -291,6 +291,8 @@ private function sanitize_element( DOMElement $element ) {
 						$result
 					);
 				}
+			} elseif ( $this_child instanceof DOMProcessingInstruction ) {
+				$this->remove_invalid_child( $this_child, [ 'code' => 'invalid_processing_instruction' ] );
```
Comment (westonruter) [inline includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php]: Please also check the other DOM node types that are not allowed. For example, a `DOMCdataSection` is not allowed in AMP:

image

Try adding checks for all of the various `dom` classes that can be generated by the HTML DOM parser: https://www.php.net/manual/en/book.dom.php

Perhaps `DOMNotation` (e.g. `<!NOTATION …>`), `DOMEntity` (e.g. `<!ENTITY …>`), and `DOMEntityReference` (e.g. `&foo;`)? Not every DOM class (or [node type](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType)) is possible to be instantiated from parsing, but please check them for good measure.

Comment (pierlon) [reply includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php]: According to the [DOM standard](https://dom.spec.whatwg.org/#node-trees) the possible nodes are `Document`, `DocumentType`, `DocumentFragment`, `Element`, `Text`, `ProcessingInstruction`, and `Comment`, which I think is all we need to consider.

The only invalid node then that should not be allowed in AMP would be `ProcessingInstruction`.

Comment (westonruter) [reply includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php]: OK, I wasn't able to cause the addition of a CDATA to result in an AMP validation error; the HTML parser actually just drops them from the document it seems. So yes, it appears we don't need to worry about them.

Comment (pierlon) [reply includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php]: > the HTML parser actually just drops them from the document 

Yes, that's what I found out as well. Reduces the work for us :smile: .
