### PR TITLE
Fix tree shaking for dynamically-added class names

### LINKED ISSUE #1490: Create new whitelist of AMP component CSS classes used to style based on state
`<amp-form>` for example has an `.amp-form-submit-success` selector, any blocks with this selector get shaken out. This is a bit different from the dynamic element whitelist (`dynamic_element_selectors`) as we want the parent selector to be ignored, not the child selector as in the dynamic element whitelist. 

E.g. `.amp-form-submit-success p { display: none }` should have a reduced version as `p { display: none; }` so it doesn't get shaken out.

`<amp-form>` classes include:
- .amp-form-initial
- .amp-form-verify
- .amp-form-verify-error
- .amp-form-submitting
- .amp-form-submit-success
- .amp-form-submit-error

### LINKED ISSUE #1946: amp-viewer class refrences removed by css cleanup process
## What's the issue?

Styling based on the class amp-viewer can not be applied, since the custom styling based on that class is removed by plugin, because amp-viewer class is not present in the static amp html file. The class is only added if the document is viewed in an AMP viewer: https://www.ampproject.org/docs/reference/components/amp-dynamic-css-classes

## How do we reproduce the issue?

**Positive Test**
1. Open: https://www.google.com/amp/s/www.cu-camper.com/de/magazin/kanada/kanada-campingplaetze/campingplaetze-in-westkanada/
2. amp-viewer class present on body element
3. classes based on amp viewer have been removed by css clean up
4. classes based on amp viewer should be present

**Negative Test**
1. Open: https://www.cu-camper.com/de/magazin/kanada/kanada-campingplaetze/campingplaetze-in-westkanada/
2. amp-viewer class not present on body element
3. classes based on amp viewer have been removed by css clean up
4. classes based on amp viewer should still be present to be applied in amp viewer state after caching

## What browsers are affected?

All browsers.

## Which AMP version is affected?

All, since css clean up is done by plugin.

### PR DESCRIPTION
**Pull request by westonruter**
Prevent tree shaking CSS rules that use class names which are dynamically added, including those for:

* [`amp-dynamic-css-classes`](https://www.ampproject.org/docs/reference/components/amp-dynamic-css-classes) (naturally)
* [`amp-carousel`](https://www.ampproject.org/docs/reference/components/amp-carousel#styling)
* [`amp-form`](https://www.ampproject.org/docs/reference/components/amp-form#classes-and-css-hooks)
* [`amp-user-notification`](https://www.ampproject.org/docs/reference/components/amp-user-notification#styling)
* [`amp-access`](https://www.ampproject.org/docs/reference/components/amp-access)/[`amp-access-laterpay`](https://www.ampproject.org/docs/reference/components/amp-access-laterpay#styling)
* [`amp-image-lightbox`](https://www.ampproject.org/docs/reference/components/amp-image-lightbox#styling)
* [`amp-live-list`](https://www.ampproject.org/docs/reference/components/amp-live-list#styling)
* [`amp-sidebar`](https://www.ampproject.org/docs/reference/components/amp-sidebar#styling-toolbar)
* [`amp-sticky-ad`](https://www.ampproject.org/docs/reference/components/amp-sticky-ad#styling)
* [`amp-video-docking`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-video-docking/amp-video-docking.md#styling)

Fixes #1946.
Fixes #1490.

----

Build for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/2962979/amp.zip) (1.1-alpha-20190313T180459Z-d5495203)

### CODE REVIEW

File: includes/sanitizers/class-amp-style-sanitizer.php [hunk 1]
```diff
@@ -357,24 +368,146 @@ public function get_stylesheets() {
...
 	 */
 	private function get_used_class_names() {
+		if ( isset( $this->used_class_names ) ) {
+			return $this->used_class_names;
+		}
+
+		$dynamic_class_names = array(
+
+			/*
+			 * See >https://www.ampproject.org/docs/reference/components/amp-dynamic-css-classes>.
```
Comment (swissspidy) [inline includes/sanitizers/class-amp-style-sanitizer.php]:
```suggestion
			 * See <https://www.ampproject.org/docs/reference/components/amp-dynamic-css-classes>.
```
