### PR TITLE
Fix missing reusable blocks when Stories turned off

### LINKED ISSUE #3081: Reusable blocks go unavailable
### Summary 
When AMP plugin version 1.2.1 is active, the Gutenberg editor does not show the option of Reusable Blocks when you click the + symbol to add a new block

### Steps to reproduce
1. Create a test WordPress site
2. Create a post or a page, and save any test block as a Reusable block
Screenshot 2019-08-23 at 3 09 04 PM
3. Activate AMP plugin
4. Open up another post and try to add the reusable block. You will not see the group
2019-08-23 15 14 10 future-seahorse jurassic ninja ebb112ddb30a
5. Deactivate AMP plugin and open a new page in editor, you see the reusable blocks again:
2019-08-23 15 16 19 future-seahorse jurassic ninja f7419f8ea56d

### Impact of the bug
Users who had Reusable blocks before updating their AMP plugin to 1.2.1, would all of a sudden see all these blocks go missing.

### PR DESCRIPTION
**Pull request by miina**
Fixes #3081

### CODE REVIEW

File: tests/e2e/specs/stories-editor/story-templates.js [hunk 1]
```diff
@@ -22,6 +29,66 @@ describe( 'Story Templates', () => {
...
+				await page.keyboard.type( 'Reusable block!' );
+
+				await clickButtonByLabel( 'More options' );
+
+				const convertButton = await page.waitForXPath( '//button[text()="Add to Reusable Blocks"]' );
+				await convertButton.click();
+			} );
+
+			afterAll( async () => {
+				await visitAdminPage( 'edit.php', 'post_type=wp_block' );
```
Comment (miina) [inline tests/e2e/specs/stories-editor/story-templates.js]: This could use a comment for what it does (removes all reusable blocks), will add it with other fixes from review.

File: tests/e2e/utils/click-on-more-menu-item.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
+/**
+ * External dependencies
+ */
+import { first } from 'lodash';
+
+/**
+ * Clicks on More Tools & options menu item by label.
```
Comment (miina) [inline tests/e2e/utils/click-on-more-menu-item.js]: This could also use a comment that it's almost a copy from upstream but uses the more reliable way for clicking.

File: tests/e2e/specs/stories-editor/story-templates.js [hunk 3]
```diff
@@ -22,6 +29,66 @@ describe( 'Story Templates', () => {
 
 			await expect( page ).toMatchElement( '.block-editor-inserter__no-results' );
 		} );
+
+		describe( 'With non-tempale Reusable block', () => {
```
Comment (swissspidy) [inline tests/e2e/specs/stories-editor/story-templates.js]: `tempale` -> `template`

File: tests/e2e/specs/stories-editor/story-templates.js [hunk 4]
```diff
@@ -22,6 +29,67 @@ describe( 'Story Templates', () => {
...
+		describe( 'With non-template Reusable block', () => {
+			// Add Reusable block.
+			beforeAll( async () => {
+				await createNewPost();
+
+				const isTopToolbarEnabled = await page.$eval( '.edit-post-layout', ( layout ) => {
+					return layout.classList.contains( 'has-fixed-toolbar' );
+				} );
+				if ( ! isTopToolbarEnabled ) {
+					await clickOnMoreMenuItem( 'Top Toolbar' );
```
Comment (swissspidy) [inline tests/e2e/specs/stories-editor/story-templates.js]: `clickBlockToolbarButton` didn't work?

Comment (miina) [reply tests/e2e/specs/stories-editor/story-templates.js]: Nope, unfortunately not.
