### PR TITLE
[AMP Stories] Remove image caption by default.

### LINKED ISSUE #2113: [AMP Stories] Initial attachment caption for image block unexpectedly appears in story on frontend when unmodified
Given an image that has a caption populated in the media library:

image

In the editor this caption is not displayed and the caption toggle is turned off (by default):

image

Nevertheless, on the frontend the caption is being displayed:

image

If I toggle the caption on and off then it is truly removed as expected.

It seems that when adding an image from the media library, the caption's `figcaption` is present in the markup even though the toggle is off, so it is hidden. Toggling the caption on and off again seems to clear out the underlying `figcaption`.

### PR DESCRIPTION
**Pull request by miina**
Fixes #2113 & #2114.

Clears the image caption by default.
Style caption in the FE.

### CODE REVIEW

File: assets/src/components/with-amp-story-settings.js [hunk 1]
```diff
@@ -173,6 +173,11 @@ export default createHigherOrderComponent(
 				rotationAngle,
 			} = attributes;
 
+			// If we have an image with pre-set caption we should remove it.
+			if ( isImageBlock && ! ampShowImageCaption && attributes.caption && 0 !== attributes.caption.length ) {
+				props.setAttributes( { caption: '' } );
```
Comment (swissspidy) [inline assets/src/components/with-amp-story-settings.js]: Can just use `setAttributes` directly FWIW
