### PR TITLE
Fix Latest Stories block styling; prevent registering block when Stories not enabled

### LINKED ISSUE #2300: Latest Stories Block: Missing CSS
When inserting the "Latest Stories" block, the block is completely unstyled:

Screenshot 2019-05-13 at 18 05 07

The CSS is added when saving and reloading the post:

Screenshot 2019-05-13 at 18 05 16

### PR DESCRIPTION
**Pull request by kienstra**
* Applies Weston's suggestion of checking in `componentWillMount()` for whether the stylesheet is present
* Uses `wp_localize_script` to make the URL of `amp-story-card.css` available. Maybe there's a better way to do this.

# Before 
before-no-styling

# After
after-styling-present

Fixes #2300

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @swissspidy and @westonruter,
Could you please review this PR for #2300? 

Thanks, and have a great weekend.

File: includes/class-amp-story-post-type.php [hunk 1]
```diff
@@ -174,6 +174,8 @@ public static function register() {
 
 		add_action( 'enqueue_block_editor_assets', array( __CLASS__, 'enqueue_block_editor_scripts' ) );
 
+		add_action( 'enqueue_block_editor_assets', array( __CLASS__, 'export_latest_stories_block_editor_data' ), 100 );
```
Comment (swissspidy) [inline includes/class-amp-story-post-type.php]: This inline script is not needed in the stories editor.

Comment (westonruter) [reply includes/class-amp-story-post-type.php]: Fixed in cc06129

File: includes/class-amp-story-post-type.php [hunk 2]
```diff
@@ -564,6 +566,33 @@ public static function register_story_card_styling( WP_Styles $wp_styles ) {
...
+			'ver',
+			wp_styles()->registered[ self::STORY_CARD_CSS_SLUG ]->ver,
+			wp_styles()->registered[ self::STORY_CARD_CSS_SLUG ]->src
+		);
+
+		/** This filter is documented in wp-includes/class.wp-styles.php */
+		$url = apply_filters( 'style_loader_src', $url, self::STORY_CARD_CSS_SLUG );
+
+		wp_add_inline_script(
+			AMP_Editor_Blocks::SCRIPT_HANDLE,
```
Comment (swissspidy) [inline includes/class-amp-story-post-type.php]: So this is inside the `AMP_Story_Post_Type` class and adds the script to the one emitted by `AMP_Editor_Blocks` (`editor-blocks.js`), yet the actual usage of this data is in `amp-block-editor.js` which is enqueued by `AMP_Post_Meta_Box`.

Comment (westonruter) [reply includes/class-amp-story-post-type.php]: I guess I got the script handle wrong?

Comment (swissspidy) [reply includes/class-amp-story-post-type.php]: If you change the script handle you don't need cc061291c5144e3afeeffa476e2d9576898fa02f and also not the `add_action( 'enqueue_block_editor_assets', array( __CLASS__, 'export_latest_stories_block_editor_data' ), 100 );` part in `AMP_Story_Post_Type`.

Comment (westonruter) [reply includes/class-amp-story-post-type.php]: Is there a `editor-blocks.js` enqueued? I only see `amp-editor-blocks.js`

Comment (swissspidy) [reply includes/class-amp-story-post-type.php]: Sorry, I meant `amp-editor-blocks.js`

Comment (westonruter) [reply includes/class-amp-story-post-type.php]: Oh, there s both an `amp-block-editor.js` _and_ an `amp-editor-blocks.js`.

Comment (westonruter) [reply includes/class-amp-story-post-type.php]: Done in 542e5850f95609c4fcff1aef422a27eeb88bc885
