### PR TITLE
Fix endless loop with manual font sizes.

### LINKED ISSUE #2794: Choosing pre-defined font size causing error
Steps to reproduce:
- Create a text block.
- Add some text.
- Turn off the setting for amp-fit-text ("Automatically fit text to container").
- Switch the font size to one of the pre-defined sizes, e.g. to “Large” 

Screenshot 2019-07-11 at 13 26 47

AC: User should be able to set a custom font size and choose between different font sizes.

### PR DESCRIPTION
**Pull request by miina**
Fixes #2794 

Splits the conditions for executing `maybeUpdateFontSize` and `maybeUpdateBlockDimensions`.

### CODE REVIEW

File: assets/src/stories-editor/components/with-meta-block-edit.js [hunk 1]
```diff
@@ -38,18 +38,23 @@ class MetaBlockEdit extends Component {
...
-			prevProps.attributes.height === height &&
-			prevProps.attributes.width === width &&
-			isEqual( prevProps.fontSize, fontSize )
-		) {
-			return;
+		// If not selected, only change font size if height or width has changed.
+		const checkFontSize = (
+			isSelected ||
+			(
+				! isSelected &&
```
Comment (kienstra) [inline assets/src/stories-editor/components/with-meta-block-edit.js]: `! isSelected ` may not be needed, as it will only get to this point if it's `false` or 'falsey'

**Comment by kienstra** [comment]
**Approved**

Hi @miina,
This looks good.

Like you mentioned, it prevents the console error when deselecting 'amp-fit-text' and changing the font size:

changing-font-size

File: assets/src/stories-editor/components/with-meta-block-edit.js (hunk 1 above)
Comment (kienstra) [reply assets/src/stories-editor/components/with-meta-block-edit.js]: Of course, this is a very minor point.
