### PR TITLE
[amp-stories sub-task] Sanitize AMP Stories.

### LINKED ISSUE #1569: Address core AMP plugin Compatibility for AMP stories
**As an AMP story creator, I would like to ensure my AMP stories are validated, and error free, and the interface provides me with feedback or validation information, to update my stories to include all required elements for AMP.**
 - [ ] _AC 1:_ Surface AMP Errors and Validation inside the Stories Editor
 - [ ] _AC 2:_  Add conditional validation to meet the AMP Stories spec. e.g.
   - [ ] _AC 3:_ Featured image (validation to require this)
   - [ ] _AC 4:_ Missing properties inside tags
   - [ ] _AC 4:_ Poster image in Video
   - [ ] _AC 4:_ Disallowing Illegal HTML elements
 - [ ] _AC 5:_  Show AMP errors inside the editor to match other post editing. (Note: Currently, the sanitizer errors are not reported in the interface.)
 - [ ] _AC 6:_  Published AMP stories should suppress validation errors, e.g. refine the AMP plugin sanitizers to add missing elements, strip the content that fails validation and alert the user.
    - [ ] _AC 7:_  An author should be able to save and publish AMP stories that have caught errors (as is handled by Gutenberg currently), but content should be sanitized to prevent validation errors from leaking to the front end.

### PR DESCRIPTION
**Pull request by miina**
Fixes #1569.

Note:
- [x] Needs updating `bin/amphtml.py` script to pull the descendants list automatically instead of editing the file directly.

### CODE REVIEW

File: includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php [hunk 1]
```diff
@@ -656,6 +656,15 @@ private function validate_tag_spec_for_node( $node, $tag_spec ) {
 			return false;
 		}
 
+		// @todo Since these are not just validating but sanitizing the descendant tags, should we move these two into a separate method?
+		if ( ! empty( $tag_spec[ AMP_Rule_Spec::CHILD_TAGS ] ) ) {
+			$this->remove_disallowed_children( $node, $tag_spec[ AMP_Rule_Spec::CHILD_TAGS ] );
+		}
+
+		if ( ! empty( $tag_spec[ AMP_Rule_Spec::DESCENDANT_TAG_LIST ] ) ) {
+			$this->remove_disallowed_descendants( $node, $tag_spec[ AMP_Rule_Spec::DESCENDANT_TAG_LIST ] );
```
Comment (miina) [inline includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php]: ^ @westonruter:
I added these two methods at this moment for handling the descendants, one for handling direct children only and one for all descendants. Let me know if this seems reasonable to you.

File: includes/sanitizers/class-amp-allowed-tags-generated.php [hunk 2]
```diff
@@ -3735,6 +3736,16 @@ class AMP_Allowed_Tags_Generated {
 					'requires_extension' => array(
 						'amp-story',
 					),
+					'child_tags' => array(
```
Comment (miina) [inline includes/sanitizers/class-amp-allowed-tags-generated.php]: @todo: Needs updating `bin/amphtml.py` script to pull the descendants list etc automatically instead of editing the file directly.

**Comment by westonruter** [comment]
As for why `amp-script` unit test is failing, see https://github.com/Automattic/amp-wp/pull/1665#issuecomment-442527167

**Comment by westonruter** [comment]
Once #1860 is reviewed and merged, then we can merge `develop` into the `amp-stories` branch and the `amp-stories` branch into this branch, and the remaining changes should be purely about the AMP Stories editor.
