### PR TITLE
Remove handling of Jetpack shortcodes

### LINKED ISSUE #3309: Migrate Jetpack shortcode handling out of AMP plugin and into Jetpack
The AMP plugin includes shortcodes for several various embed handlers, including:

* `tweet`
* `vimeo`
* `soundcloud`
* `youtube`
* `dailymotion`
* `instagram`
 
For example, the AMP plugin includes a `vimeo` shortcode as part of its `AMP_Vimeo_Embed_Handler` for historical reasons, but over time more and more Jetpack code has been moved from the AMP plugin to… Jetpack. See #1021. This code needs to be extracted from the AMP plugin to move over to Jetpack. All such shortcode handling needs to be moved to Jetpack since the shortcodes are only being registered for AMP responses, leaving non-AMP pages without any shortcode defined.

----
Hi there!

I am trying to convert my website's theme to be fully AMP compatible. 

In the blog posts from my website, we use the Jetpack Vimeo shortcode. As the [documentation](https://en.support.wordpress.com/videos/vimeo/) states, we can use the shortcode by providing the URL or the video ID. We have used the shortcode exclusively using the [vimeo 123456] format, and it has worked as intended so far.

While testing the AMP version of my site, I noticed that the Vimeo videos were not showing. Further debugging took me to the AMP plugin, to the file `includes/embeds/class-amp-vimeo-embed.php`, to the function `shortcode` in line 71.

```php
public function shortcode( $attr ) {
	$video_id = false;

	if ( isset( $attr['id'] ) ) {
		$video_id = $attr['id'];
	} elseif ( isset( $attr['url'] ) ) {
		$video_id = $this->get_video_id_from_url( $attr['url'] );
	} elseif ( isset( $attr[0] ) ) {
		$video_id = $this->get_video_id_from_url( $attr[0] );
	} elseif ( function_exists( 'shortcode_new_to_old_params' ) ) {
		$video_id = shortcode_new_to_old_params( $attr );
	}

	if ( empty( $video_id ) ) {
		return '';
	}

	return $this->render(
		[
			'video_id' => $video_id,
		]
	);
}
```
The issue here is that the way the Jetpack documentation says it's possible to use the shortcode there is no need to use an `id` or `url` attribute, so the first two if statements do not apply to my case. Now, the third statement applies because I have submitted the Vimeo ID to the shortcode, and therefore `$attr[0]` is set. However, the statement assumes that I have passed a URL, as it calls `get_video_id_from_url`, where as I have passed an ID. 

I think this shortcode function needs to parse the `$attr` variable first, similar to how Jetpack does it:

```php
$attr = array_map(
	'intval',
	shortcode_atts(
		array(
			'id'       => 0,
			'width'    => 0,
			'height'   => 0,
			'autoplay' => 0,
			'loop'     => 0,
		),
		$atts
	)
);

if ( isset( $atts[0] ) ) {
	$attr['id'] = jetpack_shortcode_get_vimeo_id( $atts );
}

if ( ! $attr['id'] ) {
	return '<!-- vimeo error: not a vimeo video -->';
}
```

My other option is to do a search and replace on all my posts, but I think making the function be compatible with Jetpack's documentation would be easier.

Thanks!

### PR DESCRIPTION
**Pull request by kienstra**
## Summary
This plugin's [handling](https://github.com/ampproject/amp-wp/blob/ea9e6fb9d262e699ea64978794840ba9868715f6/includes/embeds/class-amp-vimeo-embed.php#L71) of Jetpack shortcodes, like `[vimeo]` and `[tweet]`, is possibly being [moved to Jetpack](https://github.com/ampproject/amp-wp/issues/3309). 

So this PR looks for the presence of a new filter that Jetpack should have. If that's present, this plugin doesn't run the logic for that shortcode.

Related to #3309

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests). (It's not really tested, but it's almost entirely deletions. So I don't think more tests are needed.)
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

File: includes/embeds/class-amp-soundcloud-embed.php [hunk 1]
```diff
@@ -23,9 +30,8 @@ class AMP_SoundCloud_Embed_Handler extends AMP_Base_Embed_Handler {
 	 * Register embed.
 	 */
 	public function register_embed() {
-		if ( function_exists( 'soundcloud_shortcode' ) ) {
-			// @todo Move this to Jetpack.
-			add_shortcode( 'soundcloud', [ $this, 'shortcode' ] );
+		if ( ! $this->is_amp_shortcode_available_in_jetpack( self::SHORTCODE_TAG ) ) {
```
Comment (westonruter) [inline includes/embeds/class-amp-soundcloud-embed.php]: Instead of this method, wouldn't it be the same to just do `! class_exists( 'Jetpack_AMP_Soundcloud_Shortcode' )`?  This code will quickly become dead code that should be removed entirely from the AMP plugin, once a new version of Jetpack has been released, so we don't need to worry too much about keeping this code around too long.

File: includes/embeds/class-amp-soundcloud-embed.php [hunk 2]
```diff
@@ -23,9 +30,8 @@ class AMP_SoundCloud_Embed_Handler extends AMP_Base_Embed_Handler {
...
+			add_shortcode( self::SHORTCODE_TAG, [ $this, 'shortcode' ] );
```
Comment (westonruter) [inline includes/embeds/class-amp-soundcloud-embed.php]: Please mark the `shortcode` methods as `@deprecated`.

File: includes/embeds/class-amp-twitter-embed.php [hunk 3]
```diff
@@ -46,7 +53,9 @@ class AMP_Twitter_Embed_Handler extends AMP_Base_Embed_Handler {
 	 * Registers embed.
 	 */
 	public function register_embed() {
-		add_shortcode( 'tweet', [ $this, 'shortcode' ] ); // Note: This is a Jetpack shortcode.
+		if ( ! $this->is_amp_shortcode_available_in_jetpack( self::SHORTCODE_TAG ) ) {
```
Comment (westonruter) [inline includes/embeds/class-amp-twitter-embed.php]: See notes above for Soundcloud.

File: includes/embeds/class-amp-vimeo-embed.php [hunk 4]
```diff
@@ -50,7 +67,9 @@ public function __construct( $args = [] ) {
 	 */
 	public function register_embed() {
 		wp_embed_register_handler( 'amp-vimeo', self::URL_PATTERN, [ $this, 'oembed' ], -1 );
-		add_shortcode( 'vimeo', [ $this, 'shortcode' ] );
+		if ( ! $this->is_amp_shortcode_available_in_jetpack( self::SHORTCODE_TAG ) ) {
```
Comment (westonruter) [inline includes/embeds/class-amp-vimeo-embed.php]: See notes above for Soundcloud.

File: tests/php/test-amp-vimeo-embed.php [hunk 5]
```diff
@@ -12,6 +12,15 @@
  */
 class AMP_Vimeo_Embed_Test extends WP_UnitTestCase {
 
+	/**
+	 * Tears down the environment after each test.
+	 *
+	 * @inheritDoc
+	 */
+	public function tearDown() {
+		remove_all_filters( 'do_shortcode_tag' );
```
Comment (westonruter) [inline tests/php/test-amp-vimeo-embed.php]: I believe this isn't necessary because filters get reset after each test anyway.

File: tests/php/test-amp-vimeo-embed.php [hunk 6]
```diff
@@ -109,4 +118,23 @@ public function test__get_scripts( $source, $expected ) {
 
 		$this->assertEquals( $expected, $scripts );
 	}
+
+	/**
+	 * Test is_amp_shortcode_available_in_jetpack.
+	 *
+	 * @covers AMP_Base_Embed_Handler::is_amp_shortcode_available_in_jetpack()
+	 */
+	public function test_is_amp_shortcode_available_in_jetpack() {
```
Comment (westonruter) [inline tests/php/test-amp-vimeo-embed.php]: This test may not be necessary. I think we can rather just check if the `Jetpack_AMP_Vimeo_Shortcode` class exists.

File: tests/php/test-amp-vimeo-embed.php (hunk 5 above)
Comment (kienstra) [reply tests/php/test-amp-vimeo-embed.php]: OK, sounds good.

File: includes/embeds/class-amp-soundcloud-embed.php (hunk 2 above)
Comment (kienstra) [reply includes/embeds/class-amp-soundcloud-embed.php]: Sure, https://github.com/ampproject/amp-wp/pull/3678/commits/3e0e649706533cbe6fbf96cb5c63710f32887d93 does that.

File: tests/php/test-amp-vimeo-embed.php (hunk 5 above)
Comment (kienstra) [reply tests/php/test-amp-vimeo-embed.php]: https://github.com/ampproject/amp-wp/pull/3678/commits/3e0e649706533cbe6fbf96cb5c63710f32887d93#diff-58db4548e89d6f4290514ec825c906ecL15 removes this `tearDown()` method.

File: includes/embeds/class-amp-vimeo-embed.php (hunk 4 above)
Comment (kienstra) [reply includes/embeds/class-amp-vimeo-embed.php]: Sure, https://github.com/ampproject/amp-wp/pull/3678/commits/b64392bf469255d7573e074a8bc0d0d1f1dc14c8 changes this

File: includes/embeds/class-amp-twitter-embed.php (hunk 3 above)
Comment (kienstra) [reply includes/embeds/class-amp-twitter-embed.php]: Sure, applied in https://github.com/ampproject/amp-wp/pull/3678/commits/b64392bf469255d7573e074a8bc0d0d1f1dc14c8

File: includes/embeds/class-amp-soundcloud-embed.php (hunk 1 above)
Comment (kienstra) [reply includes/embeds/class-amp-soundcloud-embed.php]: Sure, https://github.com/ampproject/amp-wp/pull/3678/commits/b64392bf469255d7573e074a8bc0d0d1f1dc14c8 checks whether the class exists.

File: includes/embeds/class-amp-soundcloud-embed.php [hunk 7]
```diff
@@ -116,7 +115,7 @@ private function parse_amp_component_from_iframe( $html, $url ) {
 	/**
 	 * Render shortcode.
 	 *
-	 * @todo Move this to Jetpack.
+	 * @deprecated 1.4.1 Moved to Jetpack in soundcloud_shortcode().
```
Comment (kienstra) [inline includes/embeds/class-amp-soundcloud-embed.php]: With the deletion of `add_shortcode( ... )` above, this function is dead code. Maybe it'd be good to delete it entirely.

The [PR](https://github.com/Automattic/jetpack/pull/14028) to migrate Soundcloud shortcode to Jetpack doesn't add a function that this can detect, like:

```
if ( ! function_exists( 'jetpack_soundcloud_amp_shortcode' ) ) {
        add_shortcode( 'soundcloud', [ $this, 'shortcode' ] );
}

File: includes/embeds/class-amp-twitter-embed.php [hunk 8]
```diff
@@ -28,6 +28,13 @@ class AMP_Twitter_Embed_Handler extends AMP_Base_Embed_Handler {
 	 */
 	const URL_PATTERN_TIMELINE = '#https?:\/\/twitter\.com(?:\/\#\!\/|\/)(?P<username>[a-zA-Z0-9_]{1,20})(?:$|\/(?P<type>likes|lists)(\/(?P<id>[a-zA-Z0-9_-]+))?)#i';
 
+	/**
+	 * The tag (name) of the shortcode.
+	 *
+	 * @var string
+	 */
+	const SHORTCODE_TAG = 'vimeo';
```
Comment (jeherve) [inline includes/embeds/class-amp-twitter-embed.php]: This should probably be `tweet`.

Comment (kienstra) [reply includes/embeds/class-amp-twitter-embed.php]: Ah, good point.

Comment (kienstra) [reply includes/embeds/class-amp-twitter-embed.php]: Addressed in https://github.com/ampproject/amp-wp/pull/3678/commits/ec5257ee50907b44281e8405918aa2fe1548aaf6. It turns out that the constant wasn't needed at all 😄

**Comment by kienstra** [comment]
The [Jetpack PRs](https://github.com/ampproject/amp-wp/issues/3309#issuecomment-553989965) with the migrated shortcode callbacks should be released in [8.0.0](https://github.com/Automattic/jetpack/milestone/138). So this PR probably shouldn't be released until that is.

**Comment by westonruter** [comment]
Excellent. Let's snooze this issue until `8.0.0` is released.

File: includes/embeds/class-amp-youtube-embed-handler.php [hunk 9]
```diff
@@ -51,7 +51,6 @@ public function __construct( $args = [] ) {
 	 */
 	public function register_embed() {
 		add_filter( 'embed_oembed_html', [ $this, 'filter_embed_oembed_html' ], 10, 2 );
-		add_shortcode( 'youtube', [ $this, 'shortcode' ] ); // @todo Deprecated. See <https://github.com/ampproject/amp-wp/issues/3309>.
 		add_filter( 'wp_video_shortcode_override', [ $this, 'video_override' ], 10, 2 );
```
Comment (westonruter) [inline includes/embeds/class-amp-youtube-embed-handler.php]: This `video_override` method needs to be restored.

Comment (kienstra) [reply includes/embeds/class-amp-youtube-embed-handler.php]: Ah, good point. I'll do that.

**Comment by kienstra** [comment]
It looks like I didn't resolve the conflicts very well.

File: includes/embeds/class-amp-youtube-embed-handler.php (hunk 9 above)
Comment (kienstra) [reply includes/embeds/class-amp-youtube-embed-handler.php]: It's restored in https://github.com/ampproject/amp-wp/pull/3678/commits/509704014bca92220b4c7240faf213981357878c

File: includes/embeds/class-amp-youtube-embed-handler.php [hunk 10]
```diff
@@ -257,10 +257,14 @@ public function video_override( $html, $attr ) {
 		}
 		$src             = $attr['src'];
 		$youtube_pattern = '#^https?://(?:www\.)?(?:youtube\.com/watch|youtu\.be/)#';
-		if ( 1 === preg_match( $youtube_pattern, $src ) ) {
-			return $this->shortcode( [ $src ] );
```
Comment (kienstra) [inline includes/embeds/class-amp-youtube-embed-handler.php]: I moved the small amount of logic from `shortcode()` that this used into this function, so `shortcode()` can be `@deprecated`.

**Comment by kienstra** [comment]
>However, there is one left which needs some more work from you, namely AMP_Vimeo_Embed_Handler::video_override()

Good catch. That method's call of `shortcode()` [is now replaced with](https://github.com/ampproject/amp-wp/pull/3678/commits/fdb463e531a2a47417d922df83542b99ddc9bb99) the small amount of logic from `shortcode()` that it used.

**Comment by kienstra** [comment]
The `[video]` shortcodes for YouTube and Vimeo work again.

For example:

```html
[video src="https://www.youtube.com/watch?v=NeXQEJNWO5w"]
[video src="https://vimeo.com/45879568"]
```

File: includes/embeds/class-amp-twitter-embed-handler.php [hunk 11]
```diff
@@ -64,11 +64,31 @@ public function unregister_embed() {
...
+		$this->did_convert_elements = true;
+		return AMP_HTML_Utils::build_tag(
+			$this->amp_tag,
+			[
+				'data-tweetid' => $id,
+				'layout'       => 'responsive',
+				'width'        => $this->args['width'],
+				'height'       => $this->args['height'],
+			]
+		);
```
Comment (westonruter) [inline includes/embeds/class-amp-twitter-embed-handler.php]: I don't think we need this method anymore, do we? Can't it just be emptied out, as I did in: e168813e521d0138383499a84632bc8637ae6727

```php
	/**
	 * Render oEmbed.
	 *
	 * @deprecated Since 1.1 as now the sanitize_raw_embeds() is used exclusively, allowing the
	 *             original oEmbed response to be wrapped with `amp-twitter`.
	 *
	 * @see \WP_Embed::shortcode()
	 *
	 * @return string Rendered oEmbed.
	 */
	public function oembed() {
		_deprecated_function( __METHOD__, '1.1' );
		return '';
	}
```

File: includes/embeds/class-amp-youtube-embed-handler.php [hunk 12]
```diff
@@ -124,17 +124,49 @@ private function parse_props( $html, $url, $video_id ) {
...
 	 * @return string Rendered oEmbed.
 	 */
-	public function oembed() {
+	public function oembed( $matches, $attr, $url ) {
+		unset( $matches, $attr );
 		_deprecated_function( __METHOD__, '1.5.0' );
-		return '';
+
+		return $this->shortcode( [ $url ] );
 	}
```
Comment (westonruter) [inline includes/embeds/class-amp-youtube-embed-handler.php]: Since these methods aren't used anymore, can't they just be made to return an empty string while having the `_deprecated_function()` calls? 

We might as well just remove them altogether because they aren't being used.

File: includes/embeds/class-amp-twitter-embed-handler.php (hunk 11 above)
Comment (westonruter) [reply includes/embeds/class-amp-twitter-embed-handler.php]: Actually, we might as well just remove it entirely, and it is not being used. It has been deprecated since 1.1.

File: includes/embeds/class-amp-youtube-embed-handler.php (hunk 10 above)
Comment (westonruter) [reply includes/embeds/class-amp-youtube-embed-handler.php]: Can't we just remove it altogether? If methods aren't being referenced anymore, then we should try to remove them altogether.

File: includes/embeds/class-amp-twitter-embed-handler.php (hunk 11 above)
Comment (kienstra) [reply includes/embeds/class-amp-twitter-embed-handler.php]: Good point, it's now removed in https://github.com/ampproject/amp-wp/pull/3678/commits/6ae3419ae2d2c7aae7f93fee751d4f368441b115.

File: includes/embeds/class-amp-youtube-embed-handler.php (hunk 12 above)
Comment (kienstra) [reply includes/embeds/class-amp-youtube-embed-handler.php]: Good point, https://github.com/ampproject/amp-wp/pull/3678/commits/4726922a1788e0d034e6bf5c955051c653d0231b removes `AMP_YouTube_Embed_Handler::shortcode()` and `oembed()`, as they're not used anywhere.
