### PR TITLE
Definitively fix issues with images in AMP not visually matching non-AMP version

### LINKED ISSUE #1305: `amp-img` receives an unexpected inline style of `width:100vw`
I'm currently working on making my site's theme AMP-compatible, and ran into this issue. I'm not quite sure whether this is caused by the AMP plugin, AMP itself or me doing something wrong.

I have a `figure` element with `wp-block-image alignfull` as classes, containing an image element, for which I have a style set `display: block; width: 100%; height: auto`. For some reason, when activating the AMP plugin (I'm aiming for native AMP, therefore I see it immediately after activating), the `amp-img` element with which it was replaced receives an inline style of `width: 100vw`, which then messes up that image's width.

Since I use Flexbox for the surrounding container, that container's width is appropriately increased by that image of 100vw width, essentially messing up the whole page layout for me. This is obviously more specific to my layout, but I'm wondering where the 100vw come from.

### LINKED ISSUE #1747: Featured images on Twenty Nineteen homepage appear stretched
Unlike #1656 where the image is not filling the entire width of the content, featured images in the post list of the homepage are stretching too wide on larger monitors:

image

### PR DESCRIPTION
**Pull request by westonruter**
Build of PR to test: [amp.zip](https://github.com/ampproject/amp-wp/files/3024455/amp.zip) (v1.1-alpha-20190329T203700Z-034ac82d)

This PR seeks to finally lay to rest the multitude of issues we've faced regarding `amp-img` not behaving like the corresponding `img`. A key piece to this is that the `sizes` attribute can now be removed from `amp-img` and the AMP runtime will (soon) compute it automatically; see https://github.com/ampproject/amphtml/issues/21371.

Fixes issues including:

* Featured image in Twenty Nineteen appears stretched in desktop.
* Centered image is too side.
* Align-wide images are not wide enough. 
* Align-full images are not wide enough.
* Small inline image is not displayed tiny as required.
* Image in Media/Text overflows right viewport (both normal and wide alignments).
* Resized image in Media/Text is not the right dimensions.
* Centered image in Classic block is not centered.
* Inline image in Classic block appears on its own line.

See screenshots below to compare.

Fixes #1747. Fixes #1305.
See #1656, #1104, #1237, #1086.
Closes #1939.

The post content I've been using to test is as follows. I tried to consider every scenario for where an image can appear:

```html
<!-- wp:image {"id":53,"align":"center"} -->
<div class="wp-block-image"><figure class="aligncenter"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/><figcaption>Bison: centered and not resized<br></figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>And here is an image without a caption and yet it is centered:</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":53,"align":"center","width":247,"height":161} -->
<div class="wp-block-image"><figure class="aligncenter is-resized"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53" width="247" height="161"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>And here is a centered image with a caption:</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":53,"align":"center","width":252,"height":163} -->
<div class="wp-block-image"><figure class="aligncenter is-resized"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53" width="252" height="163"/><figcaption>Resized and centered</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:image {"id":53,"align":"left","width":252,"height":163} -->
<div class="wp-block-image"><figure class="alignleft is-resized"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53" width="252" height="163"/><figcaption>Resized and left-floated</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:image {"id":53,"align":"right","width":252,"height":163} -->
<div class="wp-block-image"><figure class="alignright is-resized"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53" width="252" height="163"/><figcaption>Resized and right-floated</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! This text is in between two beasts! </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":53,"align":"wide"} -->
<figure class="wp-block-image alignwide"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/><figcaption>Wide</figcaption></figure>
<!-- /wp:image -->

<!-- wp:image {"id":53,"align":"full"} -->
<figure class="wp-block-image alignfull"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/><figcaption>Full bleed<br></figcaption></figure>
<!-- /wp:image -->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->

<!-- wp:paragraph -->
<p>Here is some text with an inline image: <img class="wp-image-53" style="width: 48px;" src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1.jpg" alt=""> See it is small?</p>
<!-- /wp:paragraph -->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->

<!-- wp:media-text {"mediaPosition":"right","mediaId":53,"mediaType":"image","isStackedOnMobile":true} -->
<div class="wp-block-media-text alignwide has-media-on-the-right is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">Bison</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Image appears to the left. It is not resized. Stacking on mobile.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:media-text {"align":"full","mediaPosition":"right","mediaId":53,"mediaType":"image","isStackedOnMobile":true} -->
<div class="wp-block-media-text alignfull has-media-on-the-right is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">Bison and full width</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Image appears to the left. It is not resized. Stacking on mobile.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:media-text {"mediaId":53,"mediaType":"image","mediaWidth":19} -->
<div class="wp-block-media-text alignwide" style="grid-template-columns:19% auto"><figure class="wp-block-media-text__media"><img src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-1024x668.jpg" alt="" class="wp-image-53"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">Bison</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Image appears to the left. It <em>is</em> resized. Stacking off mobile.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->

<p><img class="alignleft size-thumbnail wp-image-53" src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-150x150.jpg" alt="" width="150" height="150">This is a <strong>classic block</strong> that contains an image floated to the left. And there is one floated to the right here too:</p>
<p>[caption id="attachment_53" align="alignright" width="150"]<img class="size-thumbnail wp-image-53" src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-150x150.jpg" alt="" width="150" height="150"> Bison in field[/caption]</p>
<p>This is a classic block that contains an image floated to the left. This is a classic block that contains an image floated to the left. This is a classic block that contains an image floated to the left. This is a classic block that contains an image floated to the left. This is a classic block that contains an image floated to the left. This is a classic block that contains an image floated to the left. But the next image is centered:</p>
<p><img class="aligncenter wp-image-53 size-medium" src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-300x196.jpg" alt="" width="300" height="196"></p>
<p>And this centered image has a caption:</p>
<p>[caption id="attachment_53" align="aligncenter" width="300"]<img class="wp-image-53 size-medium" src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-300x196.jpg" alt="" width="300" height="196"> Bison in the field.[/caption]</p>
<p>Next line with tiny image inline:&nbsp;<img class="alignnone wp-image-53 " src="https://wordpressdev.lndo.site/content/uploads/2019/02/1200px-American_bison_k5680-1-150x150.jpg" alt="" width="16" height="16">. See how small it is?</p>
<p>Next line.</p>
```

# Desktop

<table><tr><th>Non-AMP (control)</th><th>✅ AMP with fix</th><th>🚫 AMP without fix</th></tr><tr><td valign=top>desktop-non-amp</td><td valign=top>desktop-amp-with-fix</td><td valign=top></td></tr></table>

# Mobile

<table><tr><th>Non-AMP (control)</th><th>✅ AMP with fix</th><th>🚫 AMP without fix</th></tr><tr><td valign=top>mobile-non-amp</td><td valign=top>mobile-amp-with-fix</td><td valign=top>mobile-amp-without-fix</td></tr></table>

# Classic Templates

Please note that the Classic templates generally lack styles for blocks in general, so there are some issues that aren't related to images here.

<table><tr><th>🚫 Before changes</th><th>✅ After changes</th></tr><tr><td valign=top>classic-amp-without-fix</td><td valign=top>classic-amp-with-fix</td></tr></table>

### CODE REVIEW

**Comment by westonruter** [comment]
For some reason the `alignfull` isn't rendering properly in the Gutenberg demo post: https://2019-theme.amp-wp.org/welcome-to-the-gutenberg-editor/?amp

**Comment by westonruter** [comment]
> For some reason the `alignfull` isn't rendering properly in the Gutenberg demo post: https://2019-theme.amp-wp.org/welcome-to-the-gutenberg-editor/?amp

OK, that seems fixed now by 6677c3bdf6878ce3a033ffd25464554cce66972e.

**Comment by westonruter** [comment]
As noted in https://github.com/ampproject/amphtml/issues/21371#issuecomment-478128984 I added the Bison image test post to the environment:

* ✅ Non-AMP: https://2019-theme.amp-wp.org/bison-image-test/
* ✅ AMP with fix: https://2019-theme.amp-wp.org/bison-image-test/?amp

File: includes/sanitizers/class-amp-core-theme-sanitizer.php [hunk 1]
```diff
@@ -402,30 +400,6 @@ function ( $content ) {
...
-	 * Remove the sizes attribute from thumbnail images in Twenty Nineteen.
-	 *
-	 * The AMP runtime sets an inline style on an <amp-img> based on the sizes attribute if it's present.
-	 * For example, <amp-img style="width:calc(50vw)">.
-	 * Removing the 'sizes' attribute isn't ideal, but it looks like it's not possible to override that inline style.
-	 *
-	 * @todo: remove when this is resolved: https://github.com/ampproject/amphtml/issues/17053
-	 * @since 1.0
-	 */
-	public static function remove_twentynineteen_thumbnail_image_sizes() {
```
Comment (kienstra) [inline includes/sanitizers/class-amp-core-theme-sanitizer.php]: It's great to be able to remove these workarounds!

**Comment by kienstra** [comment]
**Brief Testing**

Hi @westonruter,
This looks good overall. There doesn't look to be distortion of images, and it's really nice seeing these workarounds removed.

It looks like sometimes images are a different size in AMP and non-AMP. Though the biggest problem before was distortion, and that doesn't look to be an issue.

Steps to reproduce
1. Activate Twenty Nineteen and checkout this PR's branch 
2. Create an Image block, without changing anything like the layout or caption
3. Download a [1024 x 628 image](http://lorempixel.com/1024/668/technics/) 
4. In the Image block, click 'Upload' and select that image.
5. Expected: it appears the same size in non-AMP and AMP
6. Actual: it appears smaller in AMP

# Non-AMP
non-amp-here

# AMP
amp-narrower

**Comment by westonruter** [comment]
@kienstra I think this is just an issue with your local environment. Note the image has the class name `amp-wp-unknown-size`. Compare that with the image at https://2019-theme.amp-wp.org/bison-image-test/

image

It appears as expected.

**Comment by westonruter** [comment]
In other words, your image is failing because the plugin wasn't able to perform the HTTP request to determine the dimensions.

**Comment by kienstra** [comment]
Thanks, @westonruter. That makes sense.

I'll review this PR.

**Comment by kienstra** [comment]
**Approved**

Hi @westonruter,
This looks good. It's really that these workarounds aren't needed anymore. 

(Stealing your great table formatting [above](https://github.com/ampproject/amp-wp/pull/2036#issue-265554574))

<table><tr><th>Non-AMP</th><th>AMP with this PR</th></tr>
<tr><td valign=top>non-amp</td><td valign=top>amp</td></tr></table>

The only images that look different in AMP have `amp-wp-unknown-size` and `amp-wp-unknown-width`. That looks to be a similar issue to the one you [commented about](https://github.com/ampproject/amp-wp/pull/2036#issuecomment-479617897), possibly just the local environment.

As expected, there's no reference PR #17053 anymore in the plugin, [like here](https://github.com/ampproject/amp-wp/pull/2036/files#diff-5d05e505f93786061c2078486784c46dL455).

**Comment by westonruter** [comment]
@kienstra I'm a bit concerned to see stretching here:

image

This should not be happening even when the sizes are unknown due to `object-fit: contain`.
